### ISSUE TITLE
Remove info from app web site to minimize maintenance and prevent duplication errors

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#14]
@SunyataZero , you may want to consider removing some info from the app web site (gh-pages).

For example, removing the description and features. This could be only in the README.

Basically the goal is to minimize how many pages you have to maintain. If info in the README is updated, you don't want to have to update the app web site each time.

The same goes for the Participate page.

If you went by this suggestion, you could remove the downloads page of the app website, and replace it with a link on the home page to the [releases page](https://github.com/SunyataZero/mindfulness-at-the-computer/releases).

How do you feel about it? The app web site is nice by the way. :) I like the clean, straightforward design.

**Comment by andy5995** [comment]
On second thought, better to leave the description, so people know what the project is about. ;)

**Comment by SunyataZero** [comment]
Thank you for this suggestion, i have been thinking about it and my take has been that i'd like to keep the "ordinary user" away from anything technical (including github), i like what you are saying though of avoiding duplication and making maintanence easier (maintanence is probably my top priority when working on technical projects)

About the README file: My thinking has been that the readme file is targeting programmers and tech people, the downside with this approach is that ordinary users may expect that the readme file will contain information that is relevant to them. I've seen recommendations of having the readme file directed towards both devs and ordinary users. My attempt to solve this was to put a link at the beginning of the readme file to the application website (and hope that the ordinary user has an internet connection). And to separate so that people who are devs can read about the application on the application website, and then continue to learn about the tech by reading the readme file and the other documents in the docs/ directory

What do you think about this approach? I'm open to rethink this

**Comment by andy5995** [comment]
When I first started using shareware in the late nineties, the README was written for the end-user. I believe at a minimum, the README should start with a brief description for end-users.

I generally agree with this https://stackoverflow.com/a/2305173

But I don't see the version number as necessary, except for a README included with a release.

**Comment by andy5995** [comment]
A ticket ( #17 ) to specifically discuss the README has been opened.

**Comment by JedMeister** [comment]
There isn't really a standard... IMO, a readme should at least contain some basic info for end users, even if that is just to direct them to where the rest of the info is. @andy5995's link is good IMO. 

Whether to include the version in the readme is a personal thing (and I agree it shouldn't be necessary). On one hand, it means that it needs to be updated everytime you do a version bump. But on the other, you can generally be sure that the readme relates to the version that's stated (if it doesn't clearly note a version, you need to rely on the tag. Actually though, if you keep it super high level (as suggested on the SO answer), then you can avoid both the need to note a version and the need to regularly update it! :)

Personally, I think that rather than trying to keep end users away from code and technical details, it's better to try to make the code and technical details more accessible to end users. Speaking more generally (not specifically to this project) IMO, the best way to do that, is to provide documentation/info from different and progressively lower "altitudes". I.e the readme/website landing page, should have super high level info. The "how to" docs (which IMO should also be provided via the web page) are lower level but still not super technical. Then fairly simple technical docs for users getting started who just want to tweak stuff. And then some more comprehensive "dev" docs, perhaps including a preferred style guide and contribution guidelines.

Basically, as suggested, the Readme is more-or-less the highest level doc page! From that perspective, in some respects, your readme and website landing page (or at least the top of your landing page) should cover pretty much the same info. Looking at your current readme, I'd personally move all the install instructions to their own doc page. But I don't think that there is actually anything wrong with it currently...

Another thing that may be worthy of consideration is automating updates of the gh_page from files within the code repo (e.g. use readme, or sections from it as well as doc pages). As a gh_page is simply a raw html file, you can use a script (triggered via a cron job or better still a git hook) on an "always on" system to script syncronisation of text from your code repo, to your your gh_page. 

I notice that you are using markdown for your docs. Could I suggest that you consider rst instead?! Restructured text is another markup language which is very similar to markdown, but it's Python's native markup language. `python-docutils` provides tools to easily and cleanly convert from rst to html. That's also possible with markdown, but it's not native to python. For all things python doc related, [this](http://docs.python-guide.org/en/latest/writing/documentation/) is a fantastic resource IMO!

**Comment by JedMeister** [comment]
@andy5995 - oops, I missed your latest post. Perhaps my essay should have been on the other issue?!

**Comment by SunyataZero** [comment]
@JedMeister Thank you for these thoughts, i can see that i have a lot to learn! I will come back to what you've written here but have already done one thing which was "low-hanging fruit" for me: I moved out running from source into it's own file (this makes a lot of sense to me) https://github.com/SunyataZero/mindfulness-at-the-computer/commit/df2011ef974ef4bafa17f944bea4d35a7e973a70

**Comment by SunyataZero** [comment]
> Another thing that may be worthy of consideration is automating updates of the gh_page from files within the code repo (e.g. use readme, or sections from it as well as doc pages). As a gh_page is simply a raw html file, you can use a script (triggered via a cron job or better still a git hook) on an "always on" system to script syncronisation of text from your code repo, to your your gh_page.

Yes, there is even support for this from github, you can choose to generate a website from the readme file, this is something i experimented with early on in the project. (I got stuck though when trying to create multiple pages)

**Comment by SunyataZero** [comment]
> I notice that you are using markdown for your docs. Could I suggest that you consider rst instead?! Restructured text is another markup language which is very similar to markdown, but it's Python's native markup language. python-docutils provides tools to easily and cleanly convert from rst to html. That's also possible with markdown, but it's not native to python. For all things python doc related, this is a fantastic resource IMO!

Thank you for this link, i hadn't seen this page but have read sections of the hitchhikers guide. rst makes sense since it's native to Python, the only reason i started using markdown is because i'm more comfortable with it, so making this switch i think would make sense

**Comment by SunyataZero** [comment]
In general the end user i'm imaging in front of me is a 65-year old woman, someone who could be confused by seeing technical details. Therefore i'm trying to separate information about the application and how it works from a user perspective from the technical parts. I know this is not always done in many project i've seen but i think just seeing things that the user doesn't understand could trigger some anxiety. I do link to running from source though from the application website (thank you for the tip of moving this out). I'm open to rethinking this though, and i'm sure i have much to learn. Kind Regards, Tord

**Comment by JedMeister** [comment]
> Yes, there is even support for this from github, you can choose to generate a website from the readme file, this is something i experimented with early on in the project. (I got stuck though when trying to create multiple pages)

TBH, I've never played with that functionality on GH. But I'm a Linux sys admin, so writing a little bash script to do stuff like that is second nature to me. If you clarify the bits you want from what repo text files and what pages you want them to go on, then I could probably bash something together?! (Pardon the pun...)

>Thank you for this link, i hadn't seen this page but have read sections of the hitchhikers guide. rst makes sense since it's native to Python, the only reason i started using markdown is because i'm more comfortable with it, so making this switch i think would make sense

You are most welcome. FWIW, speaking from personal experience, it's possible to make rst that renders nicely on GitHub but still easily converts to html. For example, one of our projects docs is in rst, e.g. the [raw rst](https://raw.githubusercontent.com/turnkeylinux/confconsole/master/docs/Lets_encrypt.rst), the same rst [rendered by GH](https://github.com/turnkeylinux/confconsole/blob/master/docs/Lets_encrypt.rst) and the same rst again, converted to html (with some automated url adjustments) and hosted on our [website](https://www.turnkeylinux.org/docs/confconsole/letsencrypt).

>In general the end user i'm imaging in front of me is a 65-year old woman, someone who could be confused by seeing technical details. Therefore i'm trying to separate information about the application and how it works from a user perspective from the technical parts. I know this is not always done in many project i've seen but i think just seeing things that the user doesn't understand could trigger some anxiety. I do link to running from source though from the application website (thank you for the tip of moving this out). I'm open to rethinking this though, and i'm sure i have much to learn. Kind Regards, Tord

No worries at all mate. It's your project and I don't have any real agenda, just keen to share my opinion. If it's a useful perspective, that's ideal, if you want to implement my ideas, even better. But I have no expectation that you'll do everything I suggest. TBH, I don't even mind if you don't implement any of them! :smile:

**Comment by SunyataZero** [comment]
Thank you for all your help, i have a feeling that i may end up implementing most of what you are saying, i just need to learn things slowly at my own pace :)

**Comment by SunyataZero** [comment]
One option i thought about: We could include a readme.txt file as well as the readme.md file and then only include readme.md in the package built using pyinstaller

**Comment by SunyataZero** [comment]
Closing this as there is currently almost no overlap between the readme and the website
