### ISSUE TITLE
Offline Help crashes app

### ISSUE THREAD

**Issue by nicolehli** [SunyataZero/mindfulness-at-the-computer#31]
When I click offline help form Help tab at the top, I get error messages and application will crash. I fetched and pull from upstream before testing this. Anyone else get this? Just want to log this before I forget.

Version
```INFO: ===== Starting Mindfulness at the Computer - 1.0.0-alpha.4 =====
INFO: Python version: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
INFO: SQLite version: 3.14.2
INFO: PySQLite (Python module) version: 2.6.0
INFO: Qt version: 5.9.1
INFO: PyQt (Python module) version: 5.9
INFO: Mindfulness at the Computer Application version: 1.0.0-alpha.4
INFO: Mindfulness at the Computer Database schema version: 1
```

Crash
```Traceback (most recent call last):
  File "C:\Users\nicoleli\Desktop\GitHub\mindfulness-at-the-computer\mc\gui\main_win.py", line 277, in show_offline_help
    mc.gui.readme_dlg.ReadmeDialog.show_dialog(self)
  File "C:\Users\nicoleli\Desktop\GitHub\mindfulness-at-the-computer\mc\gui\readme_dlg.py", line 32, in show_dialog
    readme_dialog = ReadmeDialog(i_parent)
  File "C:\Users\nicoleli\Desktop\GitHub\mindfulness-at-the-computer\mc\gui\readme_dlg.py", line 26, in __init__
    with open(mc.mc_global.README_FILE_STR, "r") as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md' ```

**Comment by SunyataZero** [comment]
Thank you for reporting this!

I will actually remove the offline help but this is still interesting since i don't get the same problem when running (the latest version) myself, and there may be something important that i don't understand here

I had forgotten to include the readme file when building using pyinstaller, though if you run from source i'm not sure why there is a problem, maybe you are starting the application from another directory than the root? The readme.md file is given with a relative path (just "README.md" rather than "/dir1/dir2/README.md") so this might also be the issue here

In any case i will remove the offline help but will keep this issue open until we have a better understanding of what i happening

Thank you again for reporting this issue, so important to find bugs and increase the quality!

Kind Regards, Tord

**Comment by nicolehli** [comment]
You're right @SunyataZero; It works in the right directory. Must be because I was not in root where README.md was. I'll close this ticket and leave the task to remove offline help.

**Comment by SunyataZero** [comment]
@nicolehli This is a good insight that i will remember, it's important for me to remember so that i don't use these relative paths in the future, but rather build an absolute path, this should be better right @JedMeister ?
