### ISSUE TITLE
"Rest Actions -> Add" results in blank entries being added

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#4]
Trying this on Debian Linux 9 (stretch)

"Rest Actions -> Add" results in blank entries being added

If nothing is entered into the field, clicking "Add" will create blank entries.

**Comment by SunyataZero** [comment]
Thank you for reporting this!

**Comment by SunyataZero** [comment]
For newbies to the Free software world, please feel free to solve this issue, it's been marked for "first-timers-only"

### Here is a hint on how to approach this issue

For the breathing phrases there is no problem because the following code was used:
```
        text_sg = self.add_to_list_qle.text().strip()  # strip is needed to remove a newline at the end (why?)
        if not (text_sg and text_sg.strip()):
            return
```

So you can do something similar to this for the rest actions, before the rest action is added to the db:

```
    def add_rest_action_clicked(self):
        model.RestActionsM.add(
            self.rest_add_action_qle.text().strip(),
            ""
        )
        self.update_gui()
        self.list_widget.setCurrentRow(self.list_widget.count() - 1)
```

Again this is a first-timers-only issue so feel free to ask questions and i'll try to answer as best i can

Kind Regards, Tord

**Comment by toonarmycaptain** [comment]
I think I did what I needed to do :)
This is my first "fix"/commit other than adding scripts to repositories.

**Comment by SunyataZero** [comment]
Hi @toonarmycaptain and thank you for contributing, i'm glad to hear that this is your first programming commit. Kind Regards, Tord
