### ISSUE TITLE
Consider splitting front and backend code?

### ISSUE THREAD

**Issue by JedMeister** [SunyataZero/mindfulness-at-the-computer#9]
TBH, I haven't looked closely at the code, so I have no idea of the implementation overhead. Perhaps this suggestions is totally unrealistic? Apologies in advance if that's the case.

Anyway, I notice that you are using Qt4 as front end library. Whilst Qt4 is an awesome front end from a developer perspective, from a Gnome/GTK user perspective, it means installing a whole ton of additional dependencies. On my work machine, I hate having anything more installed than I really need (to keep it lean and super fast). So as a general rule I avoid installing apps which use a Qt front end.

OTOH, I totally understand why you'd want to use Qt4 as your default front end. It's cross platform, easy to use and looks great!

So, my suggestion is, perhaps it's worth considering splitting the front and back ends?! Almost like a client/server model. You could develop a basic API (and other stuff like a message queue) for the communication between them? You could then still ship the default Qt4 front end with the backend, so end users using Qt4 would never even know. 

But it would provide the flexibility of relatively easily adding alternate front ends in the future. Someone like me could develop a GTK front end (if I could be bothered! :smile:). Other ideas are a commandline front end, or perhaps even a web front end?! With that in place, it probably wouldn't be too much more work to make it an actual proper client/server, so a single backend could serve multiple front ends.

I understand that this is probably a ton of work, for very little immediate gain. But I think it would pretty cool and would add a ton of value in the longer term. Even if this isn't something that you'd like to implement now, perhaps it's worth keeping in mind if you ever do a rewrite down the track?

Just my 2c... :smile: (FWIW, I'm a bit of a server guy, so I prefer stuff with commandline interface, plus also work lots with web apps).

Regardless, great work on this, it's looking good! :+1:

**Comment by SunyataZero** [comment]
Hi and thank you for these thoughts, i appreciate it, and i'm learning from what you are writing here

Yes the application uses PyQt5, i've also tried using GTK and TkInter when i started learning about programming desktop GUI applications a year ago or so. I actually implemented the same application (another one than this) in these three different frameworks. I ended up liking PyQt5 and many people seemed to like it very much

I also share some of your concerns about the size of the application, but for me other things are more important, like maintainability for example. However i read what you wrote about creating deb packages and getting these packages to follow a standard that makes it possible for them to get into the official repos, and if i understood you in that case it's better to (or we have to) avoid bundling things in that package (like PyQt5 which i think at the moment is the only thing outside of Python). But maybe it's possible for us to just say that PyQt5/Qt5 is a dependency when making the debian packaging? (I know that PyQt5 is available through both pip and apt) If you're willing i'd like to continue this discussion here: https://gitter.im/mindfulness-at-the-computer/packaging

Getting back to your general point of making the application available on multiple platforms and separating the front-end and back-end code: I'll admit that i lack experience with this so please correct me here, but here's my understanding: The back-end code right now is a pretty small part of the application, and is contained in two files: `mc/db.py` and `mc/model.py`, so it's separated to some extent i guess, but not in pure MVC (with observers etc). Not sure but have i misunderstood your point here?

I like to create a web application some day as well, the advantage of the web is that you get access to all OS:es for free so to speak, the downside for me is JavaScript/ECMA Script which i don't know well and doesn't seem as nice to program in as Python (though i'd like to learn it! and have actually just bought a book about JavaScript)

In general my main concern is maintainability, this is often my top priority, and also reaching many users so that many people can benefit from this application

Again thank you for your thoughts, and i'm happy to continue these discussions with you!

Kind Regards, Tord

**Comment by andy5995** [comment]
@JedMeister , Hi. I think your ideas are great. I like flexibility and versatility, and long-term thinking. The problem for me is... I know very little python. :) So far I've just helping with odds-and-ends.

**Comment by JedMeister** [comment]
It's perhaps somewhat overkill right now, so I'm going to close this. Maybe just something to keep in mind if/when you do a rewrite?!

@SunyataZero - WRT to Python for webapps. It's totally doable. Actually there are quite a few MVC options. [bottle](https://bottlepy.org/docs/dev/) is superlightweight, [flask](http://flask.pocoo.org/) is still lightweight but has more features, [django](https://www.djangoproject.com/) is the gorilla. 

@andy5995 - thanks for the encouragement! :smile:  I don't know much python either, but I need to learn. My problem is I don't have much spare time at the moment.
